# Generated by Django 5.1.6 on 2025-03-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='students',
        ),
    ]
