# Generated by Django 5.1.6 on 2025-02-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_no', models.IntegerField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('mail', models.TextField()),
                ('cls', models.IntegerField()),
                ('subject', models.TextField()),
            ],
        ),
    ]
